language: go
go:
- 1.8
branches:
  only:
  - "/^v\\d.*$/"
env:
  global:
  - UPDATE_CHANNEL=alpha
  - PATH=$PATH:$GOPATH/bin
  - VERSION=$TRAVIS_BRANCH
  matrix:
  - BUILD_GOOS=linux BUILD_GOARCH=amd64
  - BUILD_GOOS=windows BUILD_GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1
# - BUILD_GOOS=linux
#   BUILD_GOARCH=arm
#   BUILD_GOARM=7
#   CC=arm-linux-gnueabi-gcc
#   CGO_ENABLED=1
# - BUILD_GOOS=linux
#   BUILD_GOARCH=arm64
#   CC=arm-linux-gnueabi-gcc
#   CGO_ENABLED=1
compiler:
- gcc
addons:
  apt:
    packages:
    - binutils-mingw-w64
    - gcc-mingw-w64
#   - gcc-arm-linux-gnueabi
#   - binutils-arm-linux-gnueabi
install:
- make install
script:
# if we define GOARCH, GOOS and GOARM directly
# it will be resetted after calling install/script function
# to avoid it we wrap the values in the BUILD-variables
- GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS GOARM=$BUILD_GOARM make release
before_deploy:
- export LABEL=$BUILD_GOOS-$BUILD_GOARCH.$UPDATE_CHANNEL
- if [ "$BUILD_GOARCH" == "arm"]; then LABEL=$LABEL"v"$BUILD_GOARM; fi
- if [ "$BUILD_GOOS" == "windows" ]; then LABEL=$LABEL".exe"; fi
- mv updater updater.$LABEL
deploy:
  provider: releases
  api_key:
    secure: BeXZlawzicuTA9QF3RFE4OhpxK9EyPifSiW5KQhPEbkcq+DJeHXi+sXLY0jH3igbBWRU+PhVoeg6KjSTWhCoPy+mj3WuQ3TOgZ660lApBxzqbVyPyEYUoS+hJUETAIi5bQLLk9lt9VnWgD2rE8GvGPbZ//0OkYOL/NcY4wdFo3h6wYbJfWwdeettkrFAce+xjbSscxo8hzShy1UyP1aHq5P4XoUBm6dGCEc9R+AFSGNb0Cb8HFE0Jnp/2ZtMfkIqI4Et9tBp72a7W0tafXJ+ZMdvLg+1+aqH7Z6mL9pStVxXlgzwyd8L8FdI8tpDp09tyfN1fJB04Zk7dF8bpt5P5TyjZqO4m4zOQvq0ZTtfgwl3ZhFX07DjYiriDnZdMt+15xkg+hTCwug6RA0sJEKbVUJ8gqI+sN+SRw/l9VJPJ79FnnpKmkaK0z3De37QhL+HGIB/m/NWeDGKpu5+XNKaRZciy+Eh7V4zE0dWJT7a4XWl3burbj7B9cF28jqQL1MOgTw+B8VNzcpCljuBJwn2rsK3rcpj4gqstCIxCyM84zmS0TAevx+uz1DSBIxKa+qcFrUg6G2Puog4OV7vOaVI9kvI2h14eGvFKw5Ui3X5c5pgrfKbiM/+J7Uq3A9iSjHBheugryiyqwlilXtSrFHt8o51P/87/qkPmVRWAAKJBl0=
  file: updater.$LABEL
  skip_cleanup: true
  on:
    tags: true
